/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Component;
import javax.swing.JInternalFrame;
import javax.swing.JTextField;

/**
 *
 * @author Lucas
 */
public class CalculodeCalagemJFrame extends javax.swing.JFrame {

  
    public CalculodeCalagemJFrame() {
       initComponents();
    }
    
    public void LimpaTela() {     
        capacidadeDeTrocaCationicaTF.setText("");
        ValorAtualDeSaturacaoDeBasesTF.setText("");
        ValorDesejadoDeSaturacaoDeBasesTF.setText("");
        PoderRelativoDeNeutralizacaoTotalTF.setText("");
        resultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        capacidadeDeTrocaCationicaTF = new javax.swing.JTextField();
        ValorAtualDeSaturacaoDeBasesTF = new javax.swing.JTextField();
        ValorDesejadoDeSaturacaoDeBasesTF = new javax.swing.JTextField();
        PoderRelativoDeNeutralizacaoTotalTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JLabel = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ValorAtualDeSaturacaoDeBasesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorAtualDeSaturacaoDeBasesTFActionPerformed(evt);
            }
        });

        PoderRelativoDeNeutralizacaoTotalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoderRelativoDeNeutralizacaoTotalTFActionPerformed(evt);
            }
        });

        jLabel2.setText("Capacidade de Troca Cationica :");

        jLabel3.setText("Valor Atual de Saturação de Bases :");

        jLabel4.setText("Valor Desejado de Saturação de Bases :");

        jLabel5.setText("Poder Relativo de Neutralização Total :");

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JLabel.setText("Resultado :");

        resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultado.setEnabled(false);
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capacidadeDeTrocaCationicaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(ValorAtualDeSaturacaoDeBasesTF)
                    .addComponent(ValorDesejadoDeSaturacaoDeBasesTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PoderRelativoDeNeutralizacaoTotalTF, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(resultado))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidadeDeTrocaCationicaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorAtualDeSaturacaoDeBasesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorDesejadoDeSaturacaoDeBasesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PoderRelativoDeNeutralizacaoTotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(limpar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PoderRelativoDeNeutralizacaoTotalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoderRelativoDeNeutralizacaoTotalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoderRelativoDeNeutralizacaoTotalTFActionPerformed

    private void ValorAtualDeSaturacaoDeBasesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorAtualDeSaturacaoDeBasesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorAtualDeSaturacaoDeBasesTFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CalculodeCalagem calculo = new CalculodeCalagem();
        float retorno;

        float CTC = Float.parseFloat(capacidadeDeTrocaCationicaTF.getText());
        float V1 = Float.parseFloat(ValorAtualDeSaturacaoDeBasesTF.getText());
        float V2 = Float.parseFloat(ValorDesejadoDeSaturacaoDeBasesTF.getText());
        float PRNT = Float.parseFloat(PoderRelativoDeNeutralizacaoTotalTF.getText());
        retorno = calculo.NecessidadeDeCalagem((int)CTC,V1,V2,PRNT);

        resultado.setText("" + retorno);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        this.LimpaTela();
    }//GEN-LAST:event_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculodeCalagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculodeCalagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculodeCalagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculodeCalagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculodeCalagemJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JTextField PoderRelativoDeNeutralizacaoTotalTF;
    private javax.swing.JTextField ValorAtualDeSaturacaoDeBasesTF;
    private javax.swing.JTextField ValorDesejadoDeSaturacaoDeBasesTF;
    private javax.swing.JTextField capacidadeDeTrocaCationicaTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
